version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: finnanceDB
    environment:
      POSTGRES_USER: c0nd0
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: finnanceDB
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: